# 1.-Write a Python program to convert a list of numeric value into a one-dimensional


In [4]:
import numpy as np
lista=list([12.23,13.32,100,36.32])
arreglo=np.array(lista)
print("arreglo: ",arreglo)

arreglo:  [ 12.23  13.32 100.    36.32]


# 2. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [12]:
vector=np.zeros(10)
vector[5]=11
print("vector: ",vector)

vector:  [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# 3. Write a Python program to create a array with values ranging from 12 to 38.

In [28]:
arreglo=np.array(np.arange(12,39))
print("arreglo: ",arreglo)

arreglo:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


# 4. Write a Python program to reverse an array (first element becomes last)

In [29]:
arreglo=arreglo[::-1]
print("arreglo: ", arreglo)

arreglo:  [38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


# 5. Write a Python program to create a 2d array with 1 on the border and 0 inside.

In [41]:
matrix=np.array(np.ones([5,5]))
matrix[1:-1,1:-1] = 0
print("matriz: \n", matrix)

matriz: 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 6. Write a Python program to add a border (filled with 0’s) around an existing array.

In [45]:
matrix = np.pad(matrix, pad_width=1, mode='constant', constant_values=0)
matrix

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

# 7.  Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern
Checkerboard pattern: [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1
0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]]

In [68]:
matrix=np.zeros([8,8])
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print("checkboard: \n",matrix)

checkboard: 
 [[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 8.-Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [72]:
farenheit= np.array(list([0, 12, 45.21 ,34, 99.91]))
print("centigrados: \n", 5*farenheit/9 - 5*32/9) 

centigrados: 
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# 9.  Write a Python program to find the set difference of two arrays. The set difference will return  the  sorted,  unique  values  in  array1  that  are  not  in  array2

In [80]:
array1= [ 0, 10, 20, 40, 60, 80]
array2= [10, 30, 40, 50, 70, 90]
print("diferencia: \n",np.setdiff1d(array1,array2))

diferencia: 
 [ 0 20 60 80]


# 10.  Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s elsewhere

In [87]:
matrix=np.diagflat([4,5,6,8])
print("diagonal: \n",matrix)

diagonal: 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
