## Ejercicios con Python

1. Write a Python program to convert a list of numeric value into a one-dimensional NumPy array. Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [50]:
import numpy as np
lista = [12.23, 13.32, 100, 36.32]
print("Lista:",lista)
arreglo = np.array(lista)
print("Arreglo Numpy unidimensional: ",arreglo)

Lista: [12.23, 13.32, 100, 36.32]
Arreglo Numpy unidimensional:  [ 12.23  13.32 100.    36.32]


2. Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [51]:
import numpy as np
zeros = np.zeros(10)
print("Arreglo de ceros: ",zeros)
print("Se cambiará el sexto valor por un 11:")
zeros[5] = 11
print("Arreglo de modificado: ",zeros)

Arreglo de ceros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Se cambiará el sexto valor por un 11:
Arreglo de modificado:  [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


3. Write a Python program to create a array with values ranging from 12 to 38.

In [52]:
import numpy as np
arreglo = np.arange(12, 39, 1)
print("Arreglo con valores del 12 al 38: ",arreglo)

Arreglo con valores del 12 al 38:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


4. Write a Python program to reverse an array (first element becomes last).

In [53]:
import numpy as np
arreglo = np.arange(12, 38, 1)
print("Arreglo Inicial: ", arreglo)
invertido = arreglo[::-1]
print("Arreglo Invertido: ", invertido)

Arreglo Inicial:  [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Arreglo Invertido:  [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


5. Write a Python program to create a 2d array with 1 on the border and 0 inside.Expected Output: Original array: [[ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.] [ 1. 1. 1. 1. 1.]] 1 on the border and 0 inside in the array [[ 1. 1. 1. 1. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 0. 0. 0. 1.] [ 1. 1. 1. 1. 1.]]

In [54]:
import numpy as np
arreglo = np.ones((5,5))
print("Arreglo Inicial: ")
print(arreglo)
arreglo[1:-1,1:-1] = 0
print("Arreglo modificado: ")
print(arreglo)


Arreglo Inicial: 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Arreglo modificado: 
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


6. Write a Python program to add a border (filled with 0’s) around an existing array.

In [55]:
import numpy as np
arreglo = np.ones((3,3))
print("Arreglo Inicial: ")
print(arreglo)
arreglo = np.pad(arreglo, pad_width=1, mode='constant', constant_values=0)
print("Arreglo modificado: ")
print(arreglo)

Arreglo Inicial: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Arreglo modificado: 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


7. Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern Checkerboard pattern: [[0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0] [0 1 0 1 0 1 0 1] [1 0 1 0 1 0 1 0]] 

hint: Explore the use of x[a :: b, :: c] = d, x[:: e, f :: g] = h, where the letters are integer numbers.

In [56]:
import numpy as np
arreglo = np.zeros((8,8),dtype=int)
arreglo[1::2,::2] = 1
arreglo[::2,1::2] = 1
print("Arreglo con patrón de ajedrez:")
print(arreglo)

Arreglo con patrón de ajedrez:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


8. Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.
Sample Array [0, 12, 45.21 ,34, 99.91]
Expected Output:
Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].

Use functions and list comprehension read the link https: // www. pythonforbeginners. com/ lists/ list-comprehensions-in-python/ , to additional information about of
list comprehension in python.

In [57]:
import numpy as np
farenheit = [0, 12.0, 45.21, 34.0, 99.91]
arreglo = np.array(farenheit)
print("Valores en grados Farenheit: ", arreglo)
print("Valores en centigrados: ", 5*arreglo/9 - 5*32/9) 

Valores en grados Farenheit:  [ 0.   12.   45.21 34.   99.91]
Valores en centigrados:  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


9. Write a Python program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. Expected Output: Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays: [ 0 20 60 80] 

Hint:explore the use of function np.setdiff1d.

In [58]:
import numpy as np
arreglo1 = [0, 10, 20, 40, 60, 80]
arreglo2 = [10, 30, 40, 50, 70, 90]
print("Arreglo 1: ", arreglo1)
print("Arreglo 2: ", arreglo2)
print("VAlores únicos del arreglo 1 que no están en el arreglo 2: ")
print(np.setdiff1d(arreglo1, arreglo2))

Arreglo 1:  [0, 10, 20, 40, 60, 80]
Arreglo 2:  [10, 30, 40, 50, 70, 90]
VAlores únicos del arreglo 1 que no están en el arreglo 2: 
[ 0 20 60 80]


10. Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s elsewhere.

In [59]:
import numpy as np
arreglo =  np.diagflat([4, 5, 6, 8])
print("Arreglo bidimensional de ceros de tamaño 4x4 con diagonal [4,5,6,8]")
print(arreglo)

Arreglo bidimensional de ceros de tamaño 4x4 con diagonal [4,5,6,8]
[[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
